config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get '/structure', to: 'pages#structure'
  get '/author', to: 'pages#author'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700|Manjari:100,400,700&display=swap" rel="stylesheet">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/author.html.erb
<h1>John Punchman</h1>

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRF8vrROxsNPtciEyTX6X7IHiB9zJz0z6d2q77b_nvKlemuIJiE">

<%= link_to "Retour à l'article", structure_path %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/structure.html.erb
<!-- https://fr.lipsum.com/ -->

<!-- 3. Structurer la page en différentes sous-parties -->
<div class="page-container">

  <!-- 4. Laisser la barre auteur pour la fin -->
  <div class="author-details">
    <div class="author-avatar">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRF8vrROxsNPtciEyTX6X7IHiB9zJz0z6d2q77b_nvKlemuIJiE">
    </div>
    <div class="author-name">
      <h3>John Punchman</h3>
    </div>
    <%= link_to "Page de l'auteur", author_path %>
    <a href="#">Autres articles de cet auteur</a>
    <a href="#" class="btn btn-success">S'abonner</a>
    <input type="text" id="input">
  </div>

  <div class="article-content">
    <!-- 1. Titre et texte en premier -->
    <h1>Lorem Ipsum</h1>

    <!-- 1. Titre et texte en premier -->
    <h2>Qu'est-ce que le Lorem Ipsum?</h2>

    <p>Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n'a pas fait que survivre cinq siècles, mais s'est aussi adapté à la bureautique informatique, sans que son contenu n'en soit modifié. Il a été popularisé dans les années 1960 grâce à la vente de feuilles Letraset contenant des passages du Lorem Ipsum, et, plus récemment, par son inclusion dans des applications de mise en page de texte, comme Aldus PageMaker.</p>

    <!-- 2. Ajouter une image -->
    <div class="article-img">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ0eT5A28-MhrOMuYGB8T_fuOd_VYIUzcRGWNyk-aQdwhm_mavI">
    </div>

    <!-- 1. Titre et texte en premier -->
    <h2>D'où vient-il?</h2>

    <p>Contrairement à une opinion répandue, le Lorem Ipsum n'est pas simplement du texte aléatoire. Il trouve ses racines dans une oeuvre de la littérature latine classique datant de 45 av. J.-C., le rendant vieux de 2000 ans. Un professeur du Hampden-Sydney College, en Virginie, s'est intéressé à un des mots latins les plus obscurs, consectetur, extrait d'un passage du Lorem Ipsum, et en étudiant tous les usages de ce mot dans la littérature classique, découvrit la source incontestable du Lorem Ipsum. Il provient en fait des sections 1.10.32 et 1.10.33 du "De Finibus Bonorum et Malorum" (Des Suprêmes Biens et des Suprêmes Maux) de Cicéron. Cet ouvrage, très populaire pendant la Renaissance, est un traité sur la théorie de l'éthique. Les premières lignes du Lorem Ipsum, "Lorem ipsum dolor sit amet...", proviennent de la section 1.10.32.
    </p>
    <p>
    L'extrait standard de Lorem Ipsum utilisé depuis le XVIè siècle est reproduit ci-dessous pour les curieux. Les sections 1.10.32 et 1.10.33 du "De Finibus Bonorum et Malorum" de Cicéron sont aussi reproduites dans leur version originale, accompagnée de la traduction anglaise de H. Rackham (1914).
    </p>
  </div>
</div>